feature: 支持token注入
TencentBlueKing/bamboo-engine pull request #172
Opened 2023-08-21 03:02 UTC by hanshuaikang

2023-10-12 03:56 UTC, normal-wls requested changes

2023-10-12 03:56 UTC, normal-wls commented on runtime/bamboo-pipeline/pipeline/eri/imp/rollback.py
> +            from pipeline.contrib.rollback.models import RollbackNodeSnapshot
apps.get_model

2023-10-12 03:56 UTC, normal-wls commented on runtime/bamboo-pipeline/pipeline/eri/imp/rollback.py
> +            from pipeline.contrib.rollback.handler import RollbackDispatcher
apps.get_model

2023-10-12 03:56 UTC, normal-wls commented on runtime/bamboo-pipeline/pipeline/contrib/rollback/tasks.py
> +    TokenRollbackTaskHandler(snapshot_id=snapshot_id, node_id=node_id, retry=retry, retry_data=retry_data).rollback()
这里看上去绕过了 dispatcher 的设计

2023-10-12 03:56 UTC, normal-wls commented on runtime/bamboo-pipeline/pipeline/contrib/rollback/tasks.py
> +            rollback_snapshot = RollbackSnapshot.objects.get(id=self.snapshot_id)
是否会有不存在的情况，看上去有删除操作

2023-10-12 03:56 UTC, normal-wls commented on runtime/bamboo-pipeline/pipeline/contrib/rollback/tasks.py
> +        if getattr(settings, "PIPELINE_ENABLE_AUTO_ROLLBACK", True):
这个功能的实现，跟PIPELINE_ENABLE_AUTO_ROLLBACK看上去不匹配
看上去不是自动回滚，是回滚后自动重新执行

2023-10-12 03:56 UTC, normal-wls commented on runtime/bamboo-pipeline/pipeline/contrib/rollback/tasks.py
> +            rollback_snapshot = RollbackSnapshot.objects.select_for_update().get(id=self.snapshot_id)
需要考虑取消预约时候和这里是否可能有竞争

2023-10-12 03:59 UTC, normal-wls commented
需要补充 pipeline_use的集成测试样例

2023-10-12 04:01 UTC, normal-wls commented
需要补充文档

2023-10-12 07:54 UTC, hanshuaikang commented on runtime/bamboo-pipeline/pipeline/contrib/rollback/handler.py
> +    def cancel_reserved_rollback(self, start_node_id, target_node_id):
我加个清理逻辑，任务执行之后会被设置成过期

2023-10-13 07:49 UTC, hanshuaikang commented on runtime/bamboo-pipeline/pipeline/contrib/rollback/tasks.py
> +            rollback_snapshot = RollbackSnapshot.objects.get(id=self.snapshot_id)
不会，删除操作只会在回滚结束的时候进行

2023-10-16 06:55 UTC, hanshuaikang commented on runtime/bamboo-pipeline/pipeline/eri/imp/process.py
> +                Process.objects.filter(
目前只会在回滚时才会执行删除逻辑

2023-10-16 07:51 UTC, hanshuaikang commented on runtime/bamboo-pipeline/pipeline/contrib/rollback/tasks.py
> +    TokenRollbackTaskHandler(snapshot_id=snapshot_id, node_id=node_id, retry=retry, retry_data=retry_data).rollback()
流程在回滚完。流程快照和节点快照会被标记为已过期，即使从这里直接触发这个任务，触发能创建出回滚所需要的快照信息不然的话应该是回滚不成功的

2023-10-18 07:28 UTC, merged