feature: 支持 Hook 事件 (closed #176)
TencentBlueKing/bamboo-engine pull request #177
Opened 2023-09-20 12:53 UTC by ZhuoZhuoCrayon

2023-09-26 09:44 UTC, normal-wls requested changes

2023-09-26 09:44 UTC, normal-wls commented on bamboo_engine/handlers/service_activity.py
> +    def dispatch(
hook_dispatch

2023-09-26 09:44 UTC, normal-wls commented on bamboo_engine/handlers/service_activity.py
> +        callback_data: typing.Optional[CallbackData] = None,
建议添加一些可变参数，方便扩展

2023-09-26 09:44 UTC, normal-wls commented on bamboo_engine/handlers/service_activity.py
> +            context_values.append(ContextValue(key=loop_output_key, type=ContextValueType.PLAIN, value=loop_value))
需要覆盖下单测

2023-09-26 09:44 UTC, normal-wls commented on runtime/bamboo-pipeline/pipeline/eri/imp/service.py
> +                hook_res = hook_func(**call_params)
当 hook_func 异常，已经有部分代码修改了 inputs 和 outputs 的内容，此时如果在外层有忽略 exception 的逻辑，则对应的值会被 set 进去，这个地方需要考虑下是否合理

2023-10-08 07:40 UTC, hanshuaikang approved these changes

2023-10-08 07:40 UTC, hanshuaikang commented on bamboo_engine/engine.py
> +        if node.type != NodeType.ServiceActivity:
对于比如暂停事件而言，网关貌似是允许暂停的，这里限制serviceActivity会导致某些本身支持的事件传递不出去

2023-10-08 07:40 UTC, hanshuaikang commented on bamboo_engine/engine.py
> +        callback_data: CallbackData = self.runtime.get_callback_data(data_id)
为什么set一下又get它呢，不可以直接用data吗

2023-10-08 07:40 UTC, hanshuaikang commented on runtime/bamboo-pipeline/pipeline/core/flow/activity/service_activity.py
> +        return self.count**2
这里有空格才是符合规范的？

2023-10-08 07:40 UTC, hanshuaikang commented on runtime/bamboo-pipeline/pipeline/eri/imp/service.py
> +        if hook_res is None:
默认为True吗，这个和现有的execute和schedule的逻辑是否一致

2023-10-12 01:58 UTC, ZhuoZhuoCrayon commented on bamboo_engine/engine.py
> +        """
> 建议添加一个配置项，让开发者可以手动开启 或关闭 dispatch

目前这个配置项放在 `if not service.need_run_hook():` 进行判断，默认关闭

2023-10-12 07:25 UTC, ZhuoZhuoCrayon commented on runtime/bamboo-pipeline/pipeline/eri/imp/service.py
> +                hook_res = hook_func(**call_params)
> 当 hook_func 异常，已经有部分代码修改了 inputs 和 outputs 的内容，此时如果在外层有忽略 exception 的逻辑，则对应的值会被 set 进去，这个地方需要考虑下是否合理

之前也在纠结这个地方，目前是先保持和 `service` `schedule` 的逻辑一致

2023-10-12 07:35 UTC, ZhuoZhuoCrayon commented on bamboo_engine/engine.py
> +        if node.type != NodeType.ServiceActivity:
> 对于比如暂停事件而言，网关貌似是允许暂停的，这里限制serviceActivity会导致某些本身支持的事件传递不出去

现在是事件和 hook 分开，Hook 目前只对 serviceActivity 做，给开发者扩展空间，而事件是都会用信号发出去的

比如：

```python
  self.runtime.node_finish(root_pipeline_id=root_pipeline_id, node_id=node.id)
  if process_info.pipeline_stack:
      self.hook_dispatch(
          top_pipeline_id=process_info.top_pipeline_id,
          root_pipeline_id=process_info.root_pipeline_id,
          node_id=node.id,
          hook=HookType.NODE_FINISH,
          node=node,
      )
```

2023-10-12 07:37 UTC, ZhuoZhuoCrayon commented on bamboo_engine/engine.py
> +        callback_data: CallbackData = self.runtime.get_callback_data(data_id)
> 为什么set一下又get它呢，不可以直接用data吗

这俩不是同一个数据类型的

```python
        return CallbackData(
            id=data_model.id, node_id=data_model.node_id, version=data_model.version, data=json.loads(data_model.data)
        )
```

2023-10-12 08:02 UTC, ZhuoZhuoCrayon commented on runtime/bamboo-pipeline/pipeline/core/flow/activity/service_activity.py
> +        return self.count**2
> 这里有空格才是符合规范的？

pre-commit 执行的结果是去掉空格

2023-10-12 12:23 UTC, ZhuoZhuoCrayon commented on runtime/bamboo-pipeline/pipeline/eri/imp/service.py
> +        if hook_res is None:
> 默认为True吗，这个和现有的execute和schedule的逻辑是否一致

一致的。

2023-10-12 14:04 UTC, ZhuoZhuoCrayon commented on bamboo_engine/engine.py
> +        callback_data: typing.Optional[CallbackData] = None,
> 建议加上一些可变参数，方便后面拓展

已添加

2023-10-12 14:05 UTC, ZhuoZhuoCrayon commented on bamboo_engine/engine.py
> +import typing
> 建议 typing.xxx的用法直接改成xxx即可，注释太长打断语意

已修改

2023-10-12 14:05 UTC, ZhuoZhuoCrayon commented on bamboo_engine/engine.py
> +    def dispatch(
> hook_dispatch

已修改

2023-10-12 14:05 UTC, ZhuoZhuoCrayon commented on bamboo_engine/handlers/service_activity.py
> +    def dispatch(
> hook_dispatch

已修改

2023-10-12 14:05 UTC, ZhuoZhuoCrayon commented on bamboo_engine/handlers/service_activity.py
> +        callback_data: typing.Optional[CallbackData] = None,
> 建议添加一些可变参数，方便扩展

已添加

2023-10-12 14:05 UTC, ZhuoZhuoCrayon commented on bamboo_engine/handlers/service_activity.py
> +            context_values.append(ContextValue(key=loop_output_key, type=ContextValueType.PLAIN, value=loop_value))
> 需要覆盖下单测

已覆盖

2023-10-12 14:06 UTC, ZhuoZhuoCrayon commented on runtime/bamboo-pipeline/pipeline/eri/imp/service.py
> +    def dispatch(
> hook_dispatch

已修改

2023-10-16 13:33 UTC, normal-wls approved these changes

2023-10-18 02:29 UTC, hanshuaikang approved these changes

2023-10-18 02:36 UTC, merged