feature: 节点计时器边界事件支持 (closed #189)
TencentBlueKing/bamboo-engine pull request #190
Opened 2023-10-30 08:37 UTC by ZhuoZhuoCrayon

2023-10-31 12:20 UTC, normal-wls requested changes

2023-10-31 12:20 UTC, normal-wls commented on runtime/bamboo-pipeline/pipeline/contrib/node_timer_event/settings.py
> +class NodeTimerEventSettngs:
有一个可能性，因为其实节点超时和计时器的实现机制很像，有没有可能把两者合并成一套配置，通过同一套配置、检测机制，不同的点只是分发之后的处理机制不同

2023-10-31 12:20 UTC, normal-wls commented on runtime/bamboo-pipeline/pipeline/contrib/node_timer_event/signals/handlers.py
> +def bamboo_engine_eri_node_state_handler(sender, node_id, to_state, version, root_id, parent_id, loop, **kwargs):
这块感觉也能跟超时的逻辑合并

2023-10-31 12:20 UTC, normal-wls commented on runtime/bamboo-pipeline/pipeline/contrib/node_timer_event/models.py
> +    def get_index__event_map(self) -> Dict[int, Dict[str, Any]]:
这里看上去没办法保证 event 一定有 index 的 key，看看是加校验还是加点注释

2023-11-01 13:11 UTC, hanshuaikang commented on runtime/bamboo-pipeline/pipeline/contrib/node_timer_event/models.py
> +        configs: List[Dict[str, Any]] = config_parse_result["data"] or []
看上下文 config_parse_result["data"] 要么不为空，要么为空，这里应该不需要 or [] 的逻辑

2023-11-01 13:11 UTC, hanshuaikang commented on runtime/bamboo-pipeline/pipeline/contrib/node_timer_event/models.py
> +class NodeTimerEventConfig(models.Model):
这里可能需要考虑下删除逻辑

2023-11-01 13:11 UTC, hanshuaikang commented on runtime/bamboo-pipeline/pipeline/contrib/node_timer_event/models.py
> +class ExpiredNodesRecord(models.Model):
可能需要考虑下删除逻辑

2023-11-09 10:26 UTC, ZhuoZhuoCrayon commented on runtime/bamboo-pipeline/pipeline/contrib/node_timer_event/handlers.py
> +@register_action("example")
已复用 Meta 类

2023-11-09 10:28 UTC, ZhuoZhuoCrayon commented on runtime/bamboo-pipeline/pipeline/contrib/node_timer_event/models.py
> +    def get_index__event_map(self) -> Dict[int, Dict[str, Any]]:
可以保证，`NodeTimerEventConfig` 写入配置的时候，会把 `index` 写入

2023-11-09 10:30 UTC, ZhuoZhuoCrayon commented on runtime/bamboo-pipeline/pipeline/contrib/node_timer_event/handlers.py
> +def register_action(action_name: str):
确实更好用，改了

2023-11-09 10:30 UTC, ZhuoZhuoCrayon commented on runtime/bamboo-pipeline/pipeline/contrib/node_timer_event/models.py
> +                    enable: bool = timer_event.get("enable") or False
不一样，比如 `{"enable": None}`

2023-11-09 10:36 UTC, ZhuoZhuoCrayon commented on runtime/bamboo-pipeline/pipeline/contrib/node_timer_event/models.py
> +class NodeTimerEventConfig(models.Model):
确实，需要删除

2023-11-09 12:23 UTC, ZhuoZhuoCrayon commented on runtime/bamboo-pipeline/pipeline/contrib/node_timer_event/models.py
> +class ExpiredNodesRecord(models.Model):
1. 过期节点记录部分已删除
2. 时间事件配置表可能业务级别有用到，新增配置项控制删除逻辑，默认删除

2023-11-09 14:20 UTC, ZhuoZhuoCrayon commented on runtime/bamboo-pipeline/pipeline/contrib/node_timer_event/settings.py
> +class NodeTimerEventSettngs:
![企业微信截图_685c065b-6ce7-46c1-a384-60b42b3bb317](https://github.com/TencentBlueKing/bamboo-engine/assets/42019787/dd458965-89b7-49dc-a1d7-c3adab20ce4e)

![企业微信截图_e1a42288-5b3f-47a6-8c7e-c34b8a5e5bc2](https://github.com/TencentBlueKing/bamboo-engine/assets/42019787/8204c6d2-4ee5-47de-8bea-237931223f08)

2023-11-20 08:42 UTC, merged